[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.9.2"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 